# exclude: ""

repos:
  # Formatting, Whitespace, etc
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
      args: ['--unsafe']  # required because hyperpyyaml has specific constructor not supported by pyyaml (i.e. !apply)
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: mixed-line-ending
      args: ['--fix=no']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
    - id: ruff
      types_or: [python, pyi]
      args: [--select, I, --fix]
    - id: ruff-format
      types_or: [python, pyi]
