# Template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package using Pip

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # --- INSTALLATIONS ---
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
  
    - name: Load cache of pip dependencies
      uses: actions/cache@master
      id: cache_requirements
      with:
        path: ${{ env.pythonLocation }}/lib/python3.8/site-packages/*
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install pip dev dependencies + package if needed
      if: steps.cache_requirements.outputs.cache-hit == 'false'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]

    - name: Install package if needed
      if: steps.cache_requirements.outputs.cache-hit == 'true'
      run: |
        python -m pip install -e . --no-dependencies

    - name: Install soundfile
      run: |
        # For soundfile dep
        sudo apt-get install libsndfile1

    # --- TESTS ---
    - name: Lint with flake8
      run: |
        python -m flake8 --config .flake8 --exit-zero --show-source --statistics src
  
    - name: Check format with Black
      run: |
        python -m black --check --diff src
      
    - name: Print install info
      run: |
        aac-datasets-info
